community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    path('', views.home, name='home'),
    path('free/', views.free, name='free_board'),
    path('free/write/', views.free_write, name='free_board_write'),
    path('free/<int:pk>/', views.free_detail, name='free_board_detail'),
    path('free/<int:pk>/edit/', views.free_edit, name='free_board_edit'),
    path('free/<int:pk>/delete/', views.free_delete, name='free_board_delete'),
    path('picture/', views.picture_board, name='picture_board'),
    path('picture/write/', views.picture_write, name='picture_board_write'),
    path('picture/<int:pk>/', views.picture_detail, name='picture_detail'),
    path('picture/<int:pk>/edit', views.picture_update, name='picture_edit'),
    path('picture/<int:pk>/delete', views.picture_delete, name='picture_delete'),
    path('mypage/', views.my_page, name='my_page'),


]

likecatProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import RedirectView

from likecatProject import settings

urlpatterns = [
    path('', RedirectView.as_view(url='community')),
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/',include('myblog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path

from myblog import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/',views.blog_search,name='blog_search'),
    path('<str:userid>/', views.myblog, name='myblog'),
    path('<str:userid>/create/', views.blog_create, name='blog_create'),
    path('<str:userid>/free/', views.blog_free, name='blog_free_board'),
    path('<str:userid>/photo/', views.blog_photo, name='blog_photo_board'),
    path('<str:userid>/free/write/', views.blog_free_write, name='blog_free_write'),
    path('<str:userid>/photo/write/', views.blog_photo_write, name='blog_photo_write'),
    path('<str:userid>/free/<int:pk>/', views.blog_free_detail, name='blog_free_detail'),
    path('<str:userid>/photo/<int:pk>/', views.blog_photo_detail, name='blog_photo_detail'),
    path('<str:userid>/free/<int:pk>/edit/', views.blog_free_edit, name='blog_free_edit'),
    path('<str:userid>/photo/<int:pk>/edit/', views.blog_photo_edit, name='blog_photo_edit'),
    path('<str:userid>/free/<int:pk>/delete/', views.blog_free_delete, name='blog_free_delete'),
    path('<str:userid>/photo/<int:pk>/delete/', views.blog_photo_delete, name='blog_photo_delete'),
    path('<str:userid>/blog_recommend/',views.blog_recommend,name='blog_recommend')
]
app_name = 'myblog'

myblog/models.py
from django.db import models

from likecatProject import settings


class MyBlog(models.Model):

    recommend = models.IntegerField(default=0)
    # 블로그 이름, 블로그에서 닉네임으로 활용
    blog_name = models.CharField(max_length=20,default="익명의 블로그")
    blog_intro= models.TextField(default="블로그 설명을 작성해주세요")
    def __str__(self):
        return self.blog_name
class MyBlogPost(models.Model):
    blog = models.ForeignKey(MyBlog, on_delete=models.CASCADE)
    author = models.CharField(max_length=25)
    subject_group = (('고양이','고양이'),('자유','자유'))
    subject = models.CharField(max_length=20, choices=subject_group)
    title = models.CharField(max_length=40)
    content = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


class MyBlogPhotoPost(models.Model):
    blog = models.ForeignKey(MyBlog, on_delete=models.CASCADE)
    author = models.CharField(max_length=25)
    subject = models.CharField(max_length=20)
    title = models.CharField(max_length=40)
    content = models.CharField(max_length=1000)
    photo = models.ImageField(upload_to='blog_photo/%Y/%m/%d/')
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


class MyBlogPostComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.OneToOneField(MyBlogPost, on_delete=models.CASCADE)
    content = models.CharField(max_length=250)
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)


class MyBlogPhotoPostComment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.OneToOneField(MyBlogPhotoPost, on_delete=models.CASCADE)
    content = models.CharField(max_length=100)
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

myblog/forms.py
from django import forms

from myblog.models import MyBlogPost, MyBlogPhotoPost


class BlogCreateForm(forms.Form):
    name = forms.CharField(max_length=20, label="블로그 이름")
    intro = forms.CharField(max_length=50, label="블로그 설명")


class BlogFreePostForm(forms.ModelForm):
    class Meta:
        model = MyBlogPost
        fields = ['subject', 'title', 'content']
        labels = {
            'subject': "주제",
            "title": "제목",
            "content": "내용",
        }
        widgets = {
            'content': forms.Textarea()
        }


class BlogFreePhotoForm(forms.ModelForm):
    class Meta:
        model = MyBlogPhotoPost
        fields = ['subject', 'title', 'content', 'photo']
        labels = {
            'subject': "주제",
            'title': "제목",
            'content': "간단한 내용",
            'photo': "사진",
        }

myblog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView

from accounts.models import MyUser
from likecatProject import settings
from myblog.forms import BlogCreateForm, BlogFreePostForm, BlogFreePhotoForm
from myblog.models import MyBlogPost, MyBlog, MyBlogPhotoPost


def home(request):
    user_list = MyUser.objects.all().order_by('-blog__recommend').filter(blog__recommend__isnull=False)
    # 로그인시만 나의블로그 render
    if request.user.is_authenticated:
        my_blog = request.user.blog
    else:
        my_blog = False
    return render(request, 'myblog/home.html', {'my_blog': my_blog, 'user_list': user_list})


def blog_search(request):
    q = request.GET.get('q', '')
    blog_user_list = MyUser.objects.all().filter(blog__blog_name__icontains=q)
    return render(request, 'myblog/blog_search.html', {'blog_user_list': blog_user_list, 'q': q})


def myblog(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)
    blog = user.blog
    return render(request, 'myblog/myblog.html', {'blog': blog, 'blog_user': user})


@login_required()
def blog_create(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)
    if request.method == "POST":
        blog = MyBlog()
        blog.recommend = 0
        blog.blog_name = request.POST.get('name')
        blog.blog_intro = request.POST.get('intro')
        blog.save()
        user.blog = blog
        if not user.avatar:
            user.avatar = request.FILES.get('avatar')
        user.save()

        return redirect('myblog:myblog', userid=userid)
    else:
        form = BlogCreateForm()
        return render(request, 'myblog/blog_create.html', {'form': form})


def blog_free(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)
    post_list = MyBlogPost.objects.all().filter(blog=user.blog)
    return render(request, 'myblog/blog_free.html', {'post_list': post_list, 'blog_user': user})


def blog_free_detail(request, userid, pk):
    blog_user = get_object_or_404(get_user_model(), username=userid)
    post = get_object_or_404(MyBlogPost, pk=pk)
    return render(request, 'myblog/blog_free_detail.html', {'post': post, 'blog_user': blog_user})


@login_required()
def blog_free_write(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)
    if request.method == "POST":
        form = BlogFreePostForm(request.POST)
        post = form.save(commit=False)
        post.blog = user.blog
        post.author = user.username
        post.save()
        return redirect('myblog:blog_free_detail', userid=userid, pk=post.pk)
    else:

        form = BlogFreePostForm()
        return render(request, 'myblog/blog.free_write.html', {'form': form})


@login_required()
def blog_free_edit(request, userid, pk):
    post = get_object_or_404(MyBlogPost, pk=pk)
    if request.method == "POST":
        form = BlogFreePostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
        return redirect('myblog:blog_free_detail', pk=pk, userid=userid)
    else:
        form = BlogFreePostForm(instance=post)
        return render(request, 'myblog/blog_free_edit.html', {'form': form})


@login_required()
def blog_free_delete(request, userid, pk):
    post = get_object_or_404(MyBlogPost, pk=pk)
    if request.method == "POST":
        post.delete()
        return redirect('myblog:blog_free_board', userid=userid)
    else:
        return render(request, 'myblog/blog_free_delete.html', {'post': post})


def blog_photo(request, userid):
    blog_user = get_object_or_404(get_user_model(), username=userid)
    post_list = MyBlogPhotoPost.objects.all().order_by('-pub_date').filter(blog=blog_user.blog)
    return render(request, 'myblog/blog_photo.html', {'post_list': post_list, 'blog_user': blog_user})


def blog_photo_detail(request, userid, pk):
    blog_user = get_object_or_404(get_user_model(), username=userid)
    post = get_object_or_404(MyBlogPhotoPost, pk=pk)
    return render(request, 'myblog/blog_photo_detail.html', {'post': post, 'blog_user': blog_user})


@login_required()
def blog_photo_write(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)

    if request.method == "POST":
        form = BlogFreePhotoForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.blog = user.blog
            post.author = user.username
            post.save()
            return redirect('myblog:blog_photo_detail', pk=post.pk, userid=userid)
    else:
        form = BlogFreePhotoForm()
        return render(request, 'myblog/blog_photo_write.html', {'form': form, 'user': user})


@login_required()
def blog_photo_edit(request, userid, pk):
    post = get_object_or_404(MyBlogPhotoPost, pk=pk)
    if request.method == "POST":
        form = BlogFreePhotoForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('myblog:blog_photo_detail', userid=userid, pk=pk)

    else:
        form = BlogFreePhotoForm(instance=post)
        return render(request, 'myblog/blog_photo_edit.html', {'form': form})


@login_required()
def blog_photo_delete(request, userid, pk):
    if request.method == "POST":
        post = get_object_or_404(MyBlogPhotoPost, pk=pk)
        post.delete()
        return redirect('myblog:blog_photo_board', userid=userid)
    else:
        return render(request, 'myblog/blog_photo_delete.html')


@login_required()
def blog_recommend(request, userid):
    user = get_object_or_404(get_user_model(), username=userid)
    if request.user.username != user.username:
        blog = user.blog
        blog.recommend += 1
        blog.save()
    return redirect('myblog:myblog', userid=userid)

myblog/templates/myblog/base.html
{% load static %}
{% load django_bootstrap5 %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% block title %}

    {% endblock %}
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>
<body>
{% if messages %}
    {% for message in messages %}
        {{ meessage.tags }} {{ message.message }}
    {% endfor %}
{% endif %}
{#내비게이션 바 사용#}
<nav class="navbar navbar-expand-lg bg-light">
    {#이거 안하면 정렬안됨 내비게이션바랑 같이 사용#}
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'community:home' %}">
            <img src="{% static 'img/home2.jpg' %}" width="60" height="45">
            고양이가 좋아!
        </a>
        <ul class="navbar-nav">

            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link active" href="/accounts/logout">로그아웃</a>
                {% else %}
                    <a class="nav-link active" href="/accounts/login/">로그인</a>
                {% endif %}
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="/accounts/register/">회원가입</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:free_board' %}">자유게시판</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:picture_board' %}">사진게시판</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'myblog:home' %}">블로그</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:my_page' %}">마이페이지</a>
            </li>
        </ul>
    </div>
</nav>


{% block content %}

{% endblock %}
</body>
</html>

myblog/templates/myblog/blog.free_write.html
{% extends 'myblog/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>{{ user.blog.blog_name }} : 블로그 글 작성</title>
{% endblock %}
{% block content %}
    <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button class="btn btn-success" type="submit">글작성</button>
    </form>
{% endblock %}

myblog/templates/myblog/blog_create.html
{% extends 'myblog/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>{{ user.username }}님의 블로그 생성</title>

{% endblock %}
{% block content %}


    {% if user.avatar %}
        <p>당신의 프로필사진</p>
        <img src="{{ user.avatar.url }}">
    {% else %}

    {% endif %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% if not user.avatar %}
            <label for="avatar" class="form-label">프로필 사진</label>
            <input name="avatar" type="file" class="form-control" id="avatar">
        {% endif %}
        <button type="submit" class="btn btn-primary">블로그 생성</button>
    </form>

{% endblock %}

myblog/templates/myblog/blog_free.html
{% extends 'myblog/base.html' %}
{% block title %}

    <title>{{ user.blog.blog_name }}블로그 자유게시판</title>
{% endblock %}
{% block content %}
    {% if post_list %}
        <div class="text-center">
            <img width="200px" height="200px" src={{ blog_user.avatar.url }}>
            <ul class="list-group">
                {% for post in post_list %}
                    <p class="list-group-item">{{ forloop.counter }}</p>
                    <a class="list-group-item"
                       href="{% url 'myblog:blog_free_detail' userid=blog_user.username pk=post.pk %}">{{ post.title }}</a>
                {% endfor %}
            </ul>
        </div>

    {% else %}
        {% if user.username == blog_user.username %}
            <p>새 포스팅을 작성해보세요!</p>
        {% endif %}
    {% endif %}
    {% if user.username == blog_user.username %}
        <a href="{% url 'myblog:blog_free_write' blog_user.username %}">글쓰기</a>
    {% endif %}
    <a href="{% url 'myblog:myblog' blog_user.username %}">돌아가기</a>
{% endblock %}

myblog/templates/myblog/blog_free_delete.html
{% extends 'myblog/base.html' %}
{% block title %}

    <title>{{ post.title }} : 블로그 게시물 삭제</title>
{% endblock %}
{% block content %}
    <p class="fs-2">글을 삭제하시겠습니까?</p>
    <form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-success">
        삭제
    </button>
    </form>


{% endblock %}

myblog/templates/myblog/blog_free_detail.html
{% extends 'myblog/base.html' %}
{% block title %}

    <title>{{ post.title }} : 블로그 게시물</title>
{% endblock %}
{% block content %}

    <p class="fs-5 text-muted">{{ post.subject }}</p>
    <p class="fs-2">{{ post.title }}</p>
    <img width="70px" height="70px" src="{{ blog_user.avatar.url }}">
    <p>{{ user.username }}</p>
    <p>{{ post.update_date }}</p>
    <p class="fs-4">{{ post.content }}</p>
    <a class="btn btn-success" href="{% url 'myblog:blog_free_board' blog_user.username %}">돌아가기</a>
    {% if user.username == blog_user.username %}
        <a class="btn btn-primary" href="{% url 'myblog:blog_free_edit' blog_user.username post.pk %}">수정</a>
        <a class="btn btn-danger" href="{% url 'myblog:blog_free_delete' blog_user.username post.pk %}">삭제</a>
    {% endif %}
{% endblock %}

myblog/templates/myblog/blog_photo.html
{% extends 'myblog/base.html' %}
{% block title %}
    <title>{{ user.blog.blog_name }} : 블로그 사진게시판</title>

{% endblock %}
{% block content %}

    {% if not post_list and user.username == blog_user.username %}
        <p>새글을 작성해보세요!</p>
    {% endif %}

    <div class="container text-center mt-4">
        <div class="row row-cols-4 g-4">
            {% for post in post_list %}
                <div class="col">
                    <div class="card">
                        <a href="{% url 'myblog:blog_photo_detail' blog_user.username post.pk %}"><img
                                class="card-img-top" width="150px" height="150px" src="{{ post.photo.url }}"></a>
                        <div class="card-body">
                            <a href="{% url 'myblog:blog_photo_detail' blog_user.username post.pk %}"
                               class="card-text">{{ post.title }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <br>
        {% if user.username == blog_user.username %}
            <a href="{% url 'myblog:blog_photo_write' blog_user.username %}" class="btn btn-primary">글쓰기</a>
        {% endif %}
        <a href="{% url 'myblog:myblog' blog_user.username %}" class="btn btn-secondary">돌아가기</a>
    </div>
{% endblock %}

myblog/templates/myblog/blog_photo_delete.html
{% extends 'myblog/base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% block title %}


{% endblock %}
{% block content %}
    <div class="text-center">
    <img width="150px" height="200px" src="{% static 'img/delete cat.png' %}">
        <h1>정말로 삭제하시겠습니까?</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">삭제</button>

        </form>
    </div>
{% endblock %}

myblog/templates/myblog/blog_photo_detail.html
{% extends 'myblog/base.html' %}
{% block title %}
    <title>{{ post.title }} : 블로그 게시글</title>

{% endblock %}
{% block content %}
    <div class="position-absolute top-50 start-50 translate-middle text-center">
        <h1 class="fs-5 text-primary">{{ post.subject }}</h1>
        <h2 class="fs-2">{{ post.title }}</h2>
        <p class="text-muted">작성자:{{ post.author }}</p>
        <img width="600px" height="400px" src="{{ post.photo.url }}">
        <p>{{ post.content }}</p>
        <p> 수정날짜:{{ post.update_date }}</p>
        <a class="btn btn-success" href="{% url 'myblog:blog_photo_board' blog_user.username %}">돌아가기</a>
        {% if user.username == blog_user.username %}
            <a class="btn btn-primary" href="{% url 'myblog:blog_photo_edit' blog_user.username post.pk %}">수정</a>
            <a class="btn btn-danger" href="{% url 'myblog:blog_photo_delete' blog_user.username post.pk %}">삭제</a>
        {% endif %}
    </div>

{% endblock %}

myblog/templates/myblog/blog_photo_edit.html
{% extends 'myblog/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>{{ post.title }} : 블로그 게시물 수정</title>

{% endblock %}
{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">수정</button>
    </form>
{% endblock %}

myblog/templates/myblog/blog_photo_write.html
{% extends 'myblog/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>{{ user.blog.blog_name }} : 블로그 글 작성</title>

{% endblock %}
{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">글쓰기</button>
    </form>

{% endblock %}

myblog/templates/myblog/blog_search.html
{% extends 'myblog/base.html' %}
{% block title %}
    <title>블로그 검색</title>
    <style>
    a {
        text-decoration: none;
    }
    </style>
{% endblock %}
{% block content %}
    {% if q and blog_user_list %}
        {% for blog_user in blog_user_list %}
            {% if blog_user.avatar %}
                <img height="200px" width="200px" src="{{ blog_user.avatar.url }}">
                <br>
            {% endif %}
            <a href="{% url 'myblog:myblog' blog_user.username %}">{{ blog_user.blog.blog_name }} 의블로그</a>
            <p>{{ blog_user.blog.blog_intro }}</p>
        {% endfor %}
    {% elif q and not blog_user_list %}
        <
        <h1>검색하신 블로그가 없습니다 : {{ q }}</h1>
    {% else %}
        <h1>검색어를 입력해주세요</h1>
    {% endif %}
    <form action="{% url 'myblog:blog_search' %}" method="GET">
        <input type="search" name="q">
        <button type="submit">검색</button>
    </form>

{% endblock %}

myblog/templates/myblog/home.html
{% extends 'myblog/base.html' %}



{% block title %}
    <style>
        a {
            text-decoration: none;
        }
    </style>
    <title>블로그</title>
{% endblock %}
{% block content %}
    <h1>블로그 랭킹</h1>
    {% for user in user_list %}
        {% if forloop.counter == 1 %}
            <a href="{% url 'myblog:myblog' user.username %}"><p class="fs-2 text-primary">
                1.{{ user.blog.blog_name }}</p></a>

            {% if user.avatar %}
                <img width="100px" height="100px" src="{{ user.avatar.url }}">
            {% endif %}
            <p>받은 추천수:{{ user.blog.recommend }}</p>

        {% elif forloop.counter == 2 %}

            <a href="{% url 'myblog:myblog' user.username %}"><p class="fs-3 text-danger">
                2.{{ user.blog.blog_name }}</p></a>
            {% if user.avatar %}
                <img width="100px" height="100px" src="{{ user.avatar.url }}">
            {% endif %}
            <p>받은 추천수:{{ user.blog.recommend }}</p>

        {% elif forloop.counter == 3 %}

            <a href="{% url 'myblog:myblog' user.username %}"><p class="fs-4 text-success">
                3.{{ user.blog.blog_name }}</p></a>
            {% if user.avatar %}
                <img width="100px" height="100px" src="{{ user.avatar.url }}">
            {% endif %}
            <p>받은 추천수:{{ user.blog.recommend }}</p>
        {% else %}

            <a href="{% url 'myblog:myblog' user.username %}"><p
                    class="text-secondary">{{ forloop.counter }}.{{ user.blog.blog_name }}</p></a>
            {% if user.avatar %}
                <img width="100px" height="100px" src="{{ user.avatar.url }}">
            {% endif %}
            <p>받은 추천수:{{ user.blog.recommend }}</p>
        {% endif %}

    {% endfor %}
    {% if my_blog %}
        <a href="{% url 'myblog:myblog' user.username %}">나의블로그</a>
    {% else %}
        {% if user.is_authenticated %}
            <a class="btn btn-primary" href="{% url 'myblog:blog_create' userid=user.username %}">블로그 만들기</a>
        {% endif %}
    {% endif %}
    <h2>블로그 검색</h2>
    <form action="{% url 'myblog:blog_search' %}" method="GET">
        <input type="search" name="q">
        <button type="submit">검색</button>
    </form>
{% endblock %}
{% if not user.is_authenticated %}

myblog/templates/myblog/myblog.html
{% extends 'myblog/base.html' %}
{% block title %}
    <title>{{ blog_user.username }}님의 블로그</title>

{% endblock %}
{% block content %}
    {% if blog_user.avatar %}
        <img width="200px" height="200px" src="{{ blog_user.avatar.url }}">
    {% endif %}
    {% if blog.blog_name %}
        <p class="fs-5">{{ blog.blog_name }}</p>
        <p class="fs-6">({{ blog_user.username }})</p>
        <p>블로그 설명:{{ blog.blog_intro }}</p>
        <a href="{% url 'myblog:blog_recommend' blog_user.username %}" class="btn btn-primary">블로그 추천
            <span class="badge text-bg-secondary">{{ blog.recommend }}</span>
        </a>


        <br>
    {% else %}
        <p>{{ blog_user.username }}</p>
        <p>블로그 설명:{{ blog.blog_intro }}</p>
    {% endif %}
    <a href="{% url 'myblog:blog_free_board' blog_user.username %}">자유게시판</a>
    <br>
    <a href="{% url 'myblog:blog_photo_board' blog_user.username %}">사진게시판</a>
{% endblock %}