accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accounts import views

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('register/',views.register,name='register'),
    path('logout/', LogoutView.as_view(next_page='community:my_page'), name='logout'),
    path('mypage_p/', views.my_page_password, name='my_page_password'),
    path('mypage_inf/', views.my_page_inf_change, name='my_page_inf_change'),
]
app_name = 'accounts'

community/urls.py
from django.urls import path
from community import views

app_name = 'community'

urlpatterns = [
    path('', views.home, name='home'),
    path('free/', views.free, name='free_board'),
    path('free/write/', views.free_write, name='free_board_write'),
    path('free/<int:pk>/', views.free_detail, name='free_board_detail'),
    path('free/<int:pk>/edit/', views.free_edit, name='free_board_edit'),
    path('free/<int:pk>/delete/', views.free_delete, name='free_board_delete'),
    path('picture/', views.picture_board, name='picture_board'),
    path('picture/write/', views.picture_write, name='picture_board_write'),
    path('picture/<int:pk>/', views.picture_detail, name='picture_detail'),
    path('picture/<int:pk>/edit', views.picture_update, name='picture_edit'),
    path('picture/<int:pk>/delete', views.picture_delete, name='picture_delete'),
    path('mypage/', views.my_page, name='my_page'),


]

likecatProject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.views.generic import RedirectView

from likecatProject import settings

urlpatterns = [
    path('', RedirectView.as_view(url='community')),
    path('admin/', admin.site.urls),
    path('community/', include('community.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/',include('myblog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/urls.py
from django.urls import path

from myblog import views

urlpatterns = [
    path('', views.home, name='home'),
    path('search/',views.blog_search,name='blog_search'),
    path('<str:userid>/', views.myblog, name='myblog'),
    path('<str:userid>/create/', views.blog_create, name='blog_create'),
    path('<str:userid>/free/', views.blog_free, name='blog_free_board'),
    path('<str:userid>/photo/', views.blog_photo, name='blog_photo_board'),
    path('<str:userid>/free/write/', views.blog_free_write, name='blog_free_write'),
    path('<str:userid>/photo/write/', views.blog_photo_write, name='blog_photo_write'),
    path('<str:userid>/free/<int:pk>/', views.blog_free_detail, name='blog_free_detail'),
    path('<str:userid>/photo/<int:pk>/', views.blog_photo_detail, name='blog_photo_detail'),
    path('<str:userid>/free/<int:pk>/edit/', views.blog_free_edit, name='blog_free_edit'),
    path('<str:userid>/photo/<int:pk>/edit/', views.blog_photo_edit, name='blog_photo_edit'),
    path('<str:userid>/free/<int:pk>/delete/', views.blog_free_delete, name='blog_free_delete'),
    path('<str:userid>/photo/<int:pk>/delete/', views.blog_photo_delete, name='blog_photo_delete'),
    path('<str:userid>/blog_recommend/',views.blog_recommend,name='blog_recommend')
]
app_name = 'myblog'

community/models.py
from django.db import models
from django.urls import reverse


class FreePost1(models.Model):
    author = models.CharField(max_length=25)
    subject = models.CharField(max_length=20)
    title = models.CharField(max_length=40)
    content = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        # detail뷰 만들면 args=[self.pk]reverse함수의 두번째인자로넣기
        return reverse('community:free_board')


class FreePicturePost(models.Model):
    author = models.CharField(max_length=25)
    subject = models.CharField(max_length=20)
    title = models.CharField(max_length=40)
    picture = models.ImageField(upload_to="picture/%Y/%m/%d/", blank=True)
    picture2 = models.ImageField(upload_to="picture/%Y/%m/%d/", blank=True)
    content = models.CharField(max_length=700)
    pub_date = models.DateTimeField(auto_now_add=True)

community/forms.py
from django import forms

from community.models import FreePost1, FreePicturePost


# class FreeWriteForm(forms.Form):
#     author = forms.CharField(max_length=25)
#     title = forms.CharField(max_length=20)
#     content = forms.CharField(max_length=500)

class FreePostForm(forms.ModelForm):
    class Meta:
        model = FreePost1
        fields = ['subject', 'title', 'content']
        widgets = {
            "subject": forms.TextInput(
                # attrs={
                #     "class":
                # }
            )
            , "title": forms.TextInput()
            , "content": forms.Textarea()

        }
        labels = {
            "subject": "주제",
            "title": "제목",
            "content": "내용",
        }


class PicturePostForm(forms.ModelForm):
    class Meta:
        model = FreePicturePost
        fields = ['subject', 'title', 'picture', 'picture2', 'content']
        widgets = {
            "subject": forms.TextInput(
                # attrs={
                #     "class":
                # }
            )
            , "title": forms.TextInput()
            , "content": forms.Textarea()

        }
        labels = {
            "subject": "주제",
            "title": "제목",
            "content": "내용",
            "picture": "사진1",
            "picture2": "사진2",
        }

community/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from accounts.forms import MyUserCreationForm, MyUserChangeForm
from community.forms import FreePostForm, PicturePostForm
from community.models import FreePost1, FreePicturePost


def home(request):
    return render(request, 'community/home.html')


def free(request):
    page = request.GET.get('page', '1')
    post_list = FreePost1.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 8)
    page_obj = paginator.get_page(page)
    context = {"page_obj": page_obj}
    return render(request, 'community/free.html', context=context)


def free_write(request):
    if request.method == "POST":
        form = FreePostForm(request.POST)
        if form.is_valid():
            # commit=False일 경우 db에 저장 x 하고 모델객체 만들어서 리턴
            # **의뜻 정확히 추가공부!
            # post = FreePost1(**form.cleaned_data)
            post = form.save(commit=False)
            # 로그인시스템만들면 익명 변경하기
            post.author = "익명"
            post.save()
        return redirect(post)
    else:
        form = FreePostForm()
    return render(request, 'community/writeForm.html', context={"form": form})


def free_detail(request, pk):
    post = get_object_or_404(FreePost1, pk=pk)
    context = {"post": post}
    return render(request, 'community/free_detail.html', context=context)


def free_delete(request, pk):
    if request.method == "POST":
        post = get_object_or_404(FreePost1, pk=pk)
        post.delete()
        return redirect('community:free_board')
    else:
        return render(request, 'community/free_delete_confirm.html')


def free_edit(request, pk):
    post = get_object_or_404(FreePost1, pk=pk)
    if request.method == "POST":
        form = FreePostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=True)
            return redirect(post)
    else:
        form = FreePostForm(instance=post)
        return render(request, 'community/free_edit.html', {"form": form, "pk": pk})


class PictureListView(ListView):
    model = FreePicturePost
    template_name = 'community/picture_board.html'
    context_object_name = 'post_list'
    # 템플릿에 들어가는 컨텍스트 이름으로 기본은 object 또는 object_list임


picture_board = PictureListView.as_view()


class PictureCreateView(CreateView):
    model = FreePicturePost
    template_name = 'community/picture_write.html'
    context_object_name = 'form'
    form_class = PicturePostForm

    # detail뷰 작성시 거기로 넘겨주기로 바꿔야함
    # success_url = reverse_lazy('community:picture_board')
    def get_success_url(self):
        return reverse('community:picture_detail', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = '익명'
        self.object.save()
        return super().form_valid(form)


class PictureUpdateView(UpdateView):
    model = FreePicturePost
    template_name = 'community/picture_update.html'
    context_object_name = 'form'
    form_class = PicturePostForm
    success_url = reverse_lazy('community:picture_board')

    def get_success_url(self):
        return reverse('community:picture_detail', args=[self.object.pk])


class PictureDetailView(DetailView):
    model = FreePicturePost
    template_name = 'community/picture_detail.html'
    context_object_name = 'post'


class PictureDeleteView(DeleteView):
    model = FreePicturePost
    template_name = 'community/picture_delete_confirm.html'
    context_object_name = 'form'
    success_url = reverse_lazy('community:picture_board')


picture_update = PictureUpdateView.as_view()
picture_detail = PictureDetailView.as_view()
picture_write = PictureCreateView.as_view()
picture_delete = PictureDeleteView.as_view()


@login_required
def my_page(request):
    return render(request, 'community/mypage.html')

community/templates/community/base.html
{% load static %}
{% load django_bootstrap5 %}

<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        a {
            text-decoration: none;
        }
    </style>
    {% block title %}

    {% endblock %}

</head>
<body>
{% if messages %}
    {% for message in messages %}
        {{ meessage.tags }} {{ message.message }}
    {% endfor %}
{% endif %}
{#내비게이션 바 사용#}
<nav class="navbar navbar-expand-lg bg-light">
    {#이거 안하면 정렬안됨 내비게이션바랑 같이 사용#}
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'community:home' %}">
            <img src="{% static 'img/home2.jpg' %}" width="60" height="45">
            고양이가 좋아!
        </a>
        <ul class="navbar-nav">

            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link active" href="/accounts/logout">로그아웃</a>
                {% else %}
                    <a class="nav-link active" href="/accounts/login/">로그인</a>
                {% endif %}
            </li>
            {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" href="/accounts/register/">회원가입</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:free_board' %}">자유게시판</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:picture_board' %}">사진게시판</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'myblog:home' %}">블로그</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'community:my_page' %}">마이페이지</a>
            </li>
        </ul>
    </div>
</nav>


{% block content %}

{% endblock %}
</body>
</html>

community/templates/community/free_delete_confirm.html
{% extends 'community/base.html' %}
{% block title %}
    <title>글삭제</title>
{% endblock %}
{% block content %}
    <p>이 글을 정말 삭제하시겠습니까?</p>
    <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">삭제</button>
    </form>
{% endblock %}

community/templates/community/free_detail.html
{% extends 'community/base.html' %}
{% block title %}
    <title>글</title>
{% endblock %}
{% block content %}
    <h1>제목:{{ post.title }}</h1>
    <p>작성자:{{ post.author }}</p>
{#    <p>내용:{{ post.content | linebreaksbr |linebreaks }}</p>#}
    <pre>내용:{{ post.content | linebreaksbr |linebreaks }}</pre>
    <a href="{% url 'community:free_board' %}" class="btn btn-success">돌아가기</a>
    <a href="{% url 'community:free_board_edit' post.pk %}" class="btn btn-primary">수정</a>
    <a href="{% url 'community:free_board_delete' post.pk %}" class="btn btn-danger">삭제</a>
{% endblock %}

community/templates/community/free_edit.html
{% extends 'community/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>글수정</title>
{% endblock %}
{% block content %}
    <form action="" method="post">
    {% bootstrap_form form %}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">
        글 수정
    </button>
    <a href="{% url 'community:free_board_detail' pk=pk %}" class="btn btn-danger">돌아가기
    </a>
    </form>
{% endblock %}

community/templates/community/home.html
{% extends 'community/base.html' %}
{% load static %}
{% block title %}

    <title>고양이 좋아</title>

{% endblock %}

{% block content %}
    <div class="position-relative">
        <div class="position-absolute top-50 start-50 translate-middle-x">
            <h1 class="fw-bold text-center">고양이 커뮤니티'고양이가 좋아'</h1>
            <img class="rounded mb-2" width="351px" height="200px" src="{% static 'img/9.jpeg' %}">
            <img class="rounded mb-2" width="351px" height="200px" src="{% static 'img/10.jpeg' %}">
            <img class="rounded" width="351px" height="200px" src="{% static 'img/11.jpeg' %}">
            <img class="rounded" width="351px" height="200px" src="{% static 'img/12.jpeg' %}">


            <br>

            <div class="d-grid gap-1">
                <a class="btn btn-primary" href="{% url 'accounts:register' %}">회원가입 하러가기</a>
                <a class="btn btn-success" href="{% url 'community:free_board' %}">자유게시판 바로가기</a>
                <a class="btn btn-warning" href="{% url 'community:picture_board' %}">사진게시판 바로가기</a>
                <a class="btn btn-secondary" href="{% url 'myblog:home' %}">블로그 바로가기</a>
            </div>
        </div>
    </div>
{% endblock %}

community/templates/community/mypage.html
{% extends 'community/mypage_base.html' %}
{% block menu %}

    <a href="{% url 'community:my_page' %}" class="list-group-item list-group-item-action active" href="">회원정보</a>
    <a href="{% url 'accounts:my_page_password' %}" class="list-group-item" href="">비밀번호 변경</a>
    {% if user.first_name and user.last_name and user.gender and user.age and user.univ and user.email and user.job %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item" href="">회원정보 수정</a>
    {% else %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item" href="">회원정보 등록</a>
    {% endif %}


{% endblock %}
{% block my_content %}

    <p>아이디:{{ user.username }}</p>
    <p>이름:{{ user.last_name }}{{ user.first_name }}</p>
    <p>성별:{{ user.gender }}</p>
    <p>나이:{{ user.age }}</p>
    <p>대학:{{ user.univ }}</p>
    <p>직업군:{{ user.job_group }}</p>
    <p>직업:{{ user.job }}</p>
    <p>이메일:{{ user.email }}</p>
{% endblock %}

community/templates/community/mypage_base.html
{% extends 'community/base.html' %}
{% load static %}
{% block title %}
    <title>마이페이지</title>
{% endblock %}

{% block content %}
    <div class="list-group">

        {% block menu %}

        {% endblock %}

    </div>

    {% block my_content %}

    {% endblock %}

{% endblock %}

community/templates/community/mypage_inf_change.html
{% extends 'community/mypage_base.html' %}
{% load django_bootstrap5 %}
{% block menu %}
    <a href="{% url 'community:my_page' %}" class="list-group-item" href="">회원정보</a>
    <a href="{% url 'accounts:my_page_password' %}" class="list-group-item " href="">비밀번호 변경</a>
    {% if user.first_name and user.last_name and user.gender and user.age and user.univ and user.email and user.job %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item list-group-item-action active" href="">회원정보
            수정</a>
    {% else %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item list-group-item-action active" href="">회원정보
            등록</a>
    {% endif %}
{% endblock %}
{% block my_content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">등록</button>
    </form>
{% endblock %}

community/templates/community/mypage_password.html
{% extends 'community/mypage.html' %}
{% load django_bootstrap5 %}
{% block menu %}
    <a href="{% url 'community:my_page' %}" class="list-group-item" href="">회원정보</a>
    <a href="{% url 'accounts:my_page_password' %}" class="list-group-item list-group-item-action active" href="">비밀번호
        변경</a>
    {% if user.first_name and user.last_name and user.gender and user.age and user.univ and user.email and user.job %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item" href="">회원정보 수정</a>
    {% else %}
        <a href="{% url 'accounts:my_page_inf_change' %}" class="list-group-item" href="">회원정보 등록</a>
    {% endif %}
{% endblock %}
{% block my_content %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">비밀번호 변경</button>
    </form>
{% endblock %}

community/templates/community/picture_board.html
{% extends 'community/base.html' %}
{% block title %}
    <title>사진게시판</title>
{% endblock %}

{% block content %}



    {#        이런방식으로는 사진게시판을 만들수없음#}
    {#        <table class="table">#}
    {#            {% for a in post_list %}#}
    {#                {% if forloop.counter < 5 %}#}
    {#                    <tr>#}
    {#                        {% for post in post_list %}#}
    {#                            <td>{{ post.picture }}</td>#}
    {#                        {% endfor %}#}
    {#                    </tr>#}
    {#                    <tr>#}
    {#                        {% for post in post_list %}#}
    {#                            <td>{{ post.title }}</td>#}
    {#                        {% endfor %}#}
    {#                    </tr>#}
    {#                {% endif %}#}
    {##}
    {#                {% if forloop.counter < 9 %}#}
    {#                    <tr>#}
    {#                        {% for post in post_list %}#}
    {#                            <td>{{ post.picture }}</td>#}
    {#                        {% endfor %}#}
    {#                    </tr>#}
    {#                    <tr>#}
    {#                        {% for post in post_list %}#}
    {#                            <td>{{ post.title }}</td>#}
    {#                        {% endfor %}#}
    {#                    </tr>#}
    {#                {% endif %}#}
    {##}
    {#            {% endfor %}#}
    {#        </table>#}
    {% if post_list %}
        {#        이부분은 https://getbootstrap.kr/docs/5.2/components/card/#%EA%B7%B8%EB%A6%AC%EB%93%9C-%EC%B9%B4%EB%93%9C 에있음#}
        <div class="row row-cols-1 row-cols-md-4">
            {% for post in post_list %}
                <div class="col">
                    <div class="card w-50 h-50 text-center">
                        <a href="{% url 'community:picture_detail' post.pk %}">
                            <img src="{{ post.picture.url }}" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <a href="{% url 'community:picture_detail' post.pk %}" class="card-title">{{ post.title }}</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <br>
    <a href="{% url 'community:picture_board_write' %}">글쓰기</a>
{% endblock %}

community/templates/community/picture_delete_confirm.html
{% extends 'community/base.html' %}
{% block title %}
    <title>사진 삭제</title>
{% endblock %}
{% block content %}
    <p>정말 삭제하시겠습니까?</p>
    <form action="" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">
        삭제
    </button>
    </form>
{% endblock %}

community/templates/community/picture_detail.html
{% extends 'community/base.html' %}
{% block title %}
    <title>사진게시물</title>
{% endblock %}
{% block content %}
    <img src="{{ post.picture.url }}">
    {% if post.picture2 %}
        <img src="{{ post.picture2.url }}">
    {% endif %}
    <p>작성자:{{ post.author }}</p>
    <pre>내용:{{ post.content }}</pre>
    <a href="{% url 'community:picture_board' %}" class="btn btn-success">돌아가기</a>
    <a href="{% url 'community:picture_edit' post.pk %}" class="btn btn-primary">수정</a>
    <a href="{% url 'community:picture_delete' post.pk %}" class="btn btn-danger">삭제</a>
{% endblock %}}

community/templates/community/picture_write.html
{% extends 'community/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>사진 올리기</title>
{% endblock %}
{% block content %}
     <form action="" method="post" enctype="multipart/form-data">
     {% csrf_token %}
         {% bootstrap_form form %}
     <button type="submit">글작성</button>
     </form>
{% endblock %}

community/templates/community/writeForm.html
{% extends 'community/base.html' %}
{% load django_bootstrap5 %}
{% block title %}
    <title>글작성</title>
{% endblock %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">글작성</button>
    </form>
{% endblock %}